<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = array(
            [
                'title' => 'Mie Goreng',
                'cover' => 'migoreng.jfif',
                'price' => '20000',
                'stock' => '1000',
                'description' => 'Mie goreng berarti "mi yang digoreng" adalah hidangan mie yang dimasak dengan digoreng tumis khas Indonesia.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'MieGoreng Special',
                'cover' => 'migorengspecial.png',
                'price' => '30000',
                'stock' => '1000',
                'description' => 'Mie Goreng Special merupakan menu makanan dari mi yang dimasak dengan cara digoreng atau ditumis dengan berbagai bumbu dan bahan isian.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Indomie Goreng',
                'cover' => 'indomie.jfif',
                'price' => '17000',
                'stock' => '1000',
                'description' => 'Indomie Goreng Mie Instan merupakan mie instant goreng yang memiliki cita rasa gurih dan lezat, sehingga membuat siapa saja menyukainya.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Indomie Kuah',
                'cover' => 'indomiekuah.jfif',
                'price' => '15000',
                'stock' => '1000',
                'description' => 'Indomie kuah amat sangat cocok dinikmati saat musim hujan, bisa menghangatkan tubuh kamu dan mengubah mood jadi lebih semangat.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi Soto',
                'cover' => 'nasisoto.jfif',
                'price' => '30000',
                'stock' => '1000',
                'description' => 'Nasi Soto  menawarkan pilihan menu Soto dengan daging sapi, ayam, udang maupun jeroan seperti ampela, usus, dan babat.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi Goreng ',
                'cover' => 'nasigoreng.jfif',
                'price' => '20000',
                'stock' => '1000',
                'description' => 'Nasi goreng adalah makanan berupa nasi yang digoreng dan dicampur dalam minyak goreng, margarin, atau mentega',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi Goreng Special',
                'cover' => 'nasigorengspecial.jfif',
                'price' => '30000',
                'stock' => '1000',
                'description' => 'Nasi Goreng Special merupakan sajian nasi yang digoreng dalam sebuah wajan atau penggorengan yang menghasilkan cita rasa berbeda karena dicampur dengan bumbu-bumbu .',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi Gurih',
                'cover' => 'nasigurih.jfif',
                'price' => '20000',
                'stock' => '1000',
                'description' => 'Nasi Guri adalah nasi yang dimasak dengan santan dengan tambahan bumbu dari rempah-rempah',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi Putih',
                'cover' => 'nasiputih.jfif',
                'price' => '100000',
                'stock' => '1000',
                'description' => ' Nasi putih adalah sumber karbohidrat utama yang menjadi makanan pokok di banyak negara,',
                'category' => 'Makanan',
            ],

            [
                'title' => 'Lontong Sayur',
                'cover' => 'lontong.jpg',
                'price' => '15000',
                'stock' => '1000',
                'description' => 'Meskipun secara tradisional, resep lontong sayur biasanya hanya terdiri dari telur dan tahu.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Perkedel',
                'cover' => 'perkedel.jfif',
                'price' => '5000',
                'stock' => '1000',
                'description' => 'Perkedel adalah makanan khas Indonesia yang terbuat dari kentang yang telah digoreng atau direbus sebelum dilumatkan,',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Ikan Nila Goreng',
                'cover' => 'nilagoreng.jfif',
                'price' => '40000',
                'stock' => '1000',
                'description' => 'Ikan Nila Goreng adalah olahan ikan yang bahan dasarnya ikan nila. ',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Telur Bebek Rebus/Sapi/Dadar',
                'cover' => 'telur.jpg',
                'price' => '40000',
                'stock' => '1000',
                'description' => 'Telur Bebek Rebus/Sapi/Dadar juga mengandung protein, lemak, dan karbohidrat, dan telur bebek juga mengandung multivitamin dan mineral.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Aneka Jus Buah',
                'cover' => 'aneka.jfif',
                'price' => '15000',
                'stock' => '1000',
                'description' => 'Aneka jus dipercaya memberikan banyak manfaat untuk tubuh. Baik itu jus yang dibuat dari buah-buahan, maupun berbagai jenis sayuran.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Jus Murni',
                'cover' => 'jus.jfif',
                'price' => '25000',
                'stock' => '1000',
                'description' => 'Jus buah murni merupakan salah satu minuman yang paling sering direkomendasikan untuk menjaga kesehatan dan kebugaran.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Jus Pelangi',
                'cover' => 'juspelangi.jfif',
                'price' => '20000',
                'stock' => '1000',
                'description' => 'Jus Pelangi adalah salah satu program detoksifikasi untuk menurunkan berat badan dengan memanfaatkan beragam jenis sayuran dan buah-buahan.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Aqua Kecil',
                'cover' => 'akecil.jfif',
                'price' => '5000',
                'stock' => '1000',
                'description' => 'Air mineral AQUA berasal dari sumber mata air yang terpilih, yaitu; melindungi ekosistem sumber airnya, menjaga kealamian',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Aqua Besar',
                'cover' => 'abesar.jfif',
                'price' => '100000',
                'stock' => '1000',
                'description' => 'Air mineral AQUA berasal dari sumber mata air yang terpilih, serta memiliki Tiga Perlindungan, yaitu; melindungi ekosistem sumber airnya, menjaga kealamian ...',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Badak',
                'cover' => 'badak.jfif',
                'price' => '12000',
                'stock' => '1000',
                'description' => 'Badak adalah minuman soda legendaris bermerek lokal',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Teh ',
                'cover' => 'tehbotol.jfif',
                'price' => '100000',
                'stock' => '1000',
                'description' => 'Teh Botol Sosro memilih bahan alami yang asli dari daun Teh yang dipetik dari kebuhnnya sendiri yang kemudian dicampur dengan bunga melati dan bunga gambir.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Kopi Hitam Panas',
                'cover' => 'kopihitam.jfif',
                'price' => '6000',
                'stock' => '1000',
                'description' => 'Kopi hitam adalah minuman yang bersifat diuretik',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Cappucino Susu Panas',
                'cover' => 'susup.jfif',
                'price' => '13000',
                'stock' => '1000',
                'description' => 'Cappucino adalah minuman berbahan dasar kopi panas dan berbusa yang dibuat dengan susu kukus dan espresso.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Cappucino Susu Dingin',
                'cover' => 'susudingin.jfif',
                'price' => '13000',
                'stock' => '1000',
                'description' => 'Es cappuccino atau cappuccini freddo adalah versi dingin dari cappuccino panas.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Teh Manis Panas',
                'cover' => 'tehmanispanas.jfif',
                'price' => '5000',
                'stock' => '1000',
                'description' => 'Teh manis adalah minuman yang terbuat dari larutan teh yang biasanya diberi gula tebu atau pemanis, sebelum minuman ini siap disajikan. ',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Teh Manis Dingin',
                'cover' => 'tehdingin.jfif',
                'price' => '100000',
                'stock' => '1000',
                'description' => 'Teh manis adalah minuman yang terbuat dari larutan teh yang biasanya diberi gula tebu atau pemanis, sebelum minuman ini siap disajikan. ',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Teh/Kopi Susu',
                'cover' => 'kopisusu.jfif',
                'price' => '13000',
                'stock' => '1000',
                'description' => 'Kopi susu adalah sajian minuman kopi yang dicampur susu',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Bir Bintang',
                'cover' => 'bir.jfif',
                'price' => '50000',
                'stock' => '1000',
                'description' => 'Bir Bintang, merupakan minuman dengan kadar alkohol bervariasi antara 0.0% hingga 5% ',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Bir Hitam',
                'cover' => 'birhitam.jfif',
                'price' => '40000',
                'stock' => '1000',
                'description' => 'Bir hitam sering dituding sebagai minuman yang tidak sehat dan lebih beralkohol dari jenis bir lainnya. ',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Nutrisari Panas',
                'cover' => 'nutrisarip.jfif',
                'price' => '8000',
                'stock' => '1000',
                'description' => 'Nutrisari adalah minuman sari buah seringkali ditemukan dalam kemasan serbuk sachet yang mudah digunakan',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Nutrisari Dingin',
                'cover' => 'nutrisaridingin.jfif',
                'price' => '100000',
                'stock' => '1000',
                'description' => 'Nutrisari adalah minuman sari buah seringkali ditemukan dalam kemasan serbuk sachet yang mudah digunakan',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coklat Panas',
                'cover' => 'coklatp.jfif',
                'price' => '8000',
                'stock' => '1000',
                'description' => 'Cokelat panas adalah minuman panas yang dibuat dari cokelat atau kakao bubuk dan gula, dengan air atau susu hangat. ',
                'category' => 'Minuman',
            ],
            [
                'title' => 'coklat Dingin',
                'cover' => 'coklatd.jfif',
                'price' => '100000',
                'stock' => '1000',
                'description' => 'Cokelat dingin adalah minuman dingin yang dibuat dari cokelat atau kakao bubuk dan gula, dengan air atau susu. ',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Hilo Panas',
                'cover' => 'hilopanas.jfif',
                'price' => '8000',
                'stock' => '1000',
                'description' => 'Hilo Panas Susu memiliki banyak manfaat untuk kesehatan, Minum susu dalam keadaan dingin atau panas sama-sama baik untuk kesehatan.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Hilo Dingin',
                'cover' => 'hilodingin.jfif',
                'price' => '100000',
                'stock' => '1000',
                'description' => 'Hilo Panas Susu memiliki banyak manfaat untuk kesehatan, Minum susu dalam keadaan dingin atau panas sama-sama baik untuk kesehatan.',
                'category' => 'Minuman',
            ],
        );
        foreach ($data as $d) {
            Product::create([
                'title' => $d['title'],
                'cover' => $d['cover'],
                'price' => $d['price'],
                'stock' => $d['stock'],
                'description' => $d['description'],
                'category' => $d['category']
            ]);
        }
    }
}
